version: '3.8'

services:
    mysql:
        image: mysql:8.0
        volumes:
            - boilerplate-db:/var/lib/mysql
        ports:
            - ${DATABASE_PORT}:3306
        environment:
            MYSQL_USER: ${DATABASE_USERNAME}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_DATABASE: ${DATABASE_NAME}
            MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
            TZ: Asia/Seoul

    app:
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - ${APP_PORT}:${APP_PORT}
        # healthcheck:
        #     test: ["CMD", "curl", "-f", "http://app:3000/docs"]
        #     interval: 10s
        #     timeout: 5s
        #     retries: 3
        #     start_period: 10s

    # redis:
    #     image: redis:alpine
    #     ports:
    #     - 6379:6379
    
    nginx:
        image: nginx:latest
        container_name: nginx
        build: ./proxy
        ports:
            - 80:80
        restart: 'always'
        depends_on:
            - app

volumes:
  boilerplate-db: